<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Kithara.DummyRegistrar</RootNamespace>
    <AssemblyName>Kithara.DummyRegistrar</AssemblyName>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.Net.Client" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\logos\src\Bardie.Logos.Contracts\Bardie.Logos.Contracts.csproj" />
  </ItemGroup>

</Project>
